import type { Metadata } from "next";
import "./globals.css";

import { Poppins, Plus_Jakarta_Sans } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['600'],
  variable: '--display-family',
});

const plus_jakarta_sans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--text-family',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${plus_jakarta_sans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
